[package]
name = "dag-json"
version = "0.1.0"
authors = ["Irakli Gozalishvili <contact@gozala.io>"]
edition = "2018"

[dependencies]
base64 = "0.12.0"
libipld-base = { path = "../base" }
serde_json = "1.0.50"
serde = { version = "1.0.106", features = ["derive"] }
thiserror = "1.0.14"

[dev-dependencies]
multihash = "0.10.1"
