[package]
name = "libipld-json"
version = "0.8.0"
authors = ["Irakli Gozalishvili <contact@gozala.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "ipld json codec"
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
base64 = "0.13.0"
libipld-core = { version = "0.8.0", path = "../core" }
multihash = "0.13.1"
serde_json = "1.0.59"
serde = { version = "1.0.117", features = ["derive"] }
