[package]
name = "libipld-cbor"
version = "0.7.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "ipld cbor codec"
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
byteorder = "1.3.4"
fnv = "1.0.7"
libipld-core = { version = "0.7.0", path = "../core" }
thiserror = "1.0.22"

[dev-dependencies]
hex = "0.4.2"
libipld-macro = { path = "../macro" }
multihash = "0.13.1"
