[package]
name = "libipld-pb"
version = "0.10.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "ipld protobuf codec"
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
libipld-core = { version = "0.10.0", path = "../core" }
prost = "0.7.0"
thiserror = "1.0.23"

[build-dependencies]
prost-build = "0.7.0"

[dev-dependencies]
libipld-macro = { path = "../macro" }
multihash = "0.13.2"
