[package]
name = "dag-pb"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "ipld protobuf codec"
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
libipld-base = { version = "0.1.0", path = "../base" }
prost = "0.6.1"
thiserror = "1.0.14"

[build-dependencies]
prost-build = "0.6.1"

[dev-dependencies]
libipld-macro = { path = "../macro" }
multihash = "0.10.1"
